Globs:
  - "src/**/*.cr"
  - "spec/**/*.cr"

Documentation/DocumentationAdmonition:
  Enabled: false

Layout/LineLength:
  Enabled: true
  MaxLength: 120

Lint/DocumentationAdmonition:
  Enabled: false

Lint/NotNil:
  Enabled: false

Lint/NotNilAfterNoBang:
  Enabled: false

Lint/SpecFilename:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

Performance/AnyInsteadOfEmpty:
  Enabled: true
  Excluded:
    - src/marten/db/management/migrations/reader.cr

Style/ParenthesesAroundCondition:
  Enabled: false

Style/QueryBoolMethods:
  Enabled: false
